# Generated by Django 5.2 on 2025-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="images/user.jpg", null=True, upload_to="avatars/"
            ),
        ),
    ]
