# Generated by Django 5.2 on 2025-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default="none", upload_to="avatars"),
            preserve_default=False,
        ),
    ]
