# Generated by Django 5.2 on 2025-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
