# Generated by Django 5.2 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(
                blank=True, default="unknown", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(
                blank=True, default="No description available", null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(
                blank=True, default="unknown", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(default="user.jpg", upload_to="movies"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=180, null=True, unique_for_date="created_at"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(
                blank=True, default="unknown", max_length=120, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(
                blank=True, default="unknown", max_length=4, null=True
            ),
        ),
    ]
