# Generated by Django 5.2 on 2025-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_movie_genre_remove_movie_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
