# Generated by Django 5.2 on 2025-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_review_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews_images/"),
        ),
    ]
