# Generated by Django 5.2 on 2025-04-10 17:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_avatar"),
        ("movies", "0005_alter_review_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.AddField(
            model_name="movie",
            name="producer",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(default="unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(default="default_bg.jpg", upload_to="movies"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(default="unknown", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(default="unknown", max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_profile",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="movies.rating",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
