# Generated by Django 5.2 on 2025-04-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_remove_movie_director_remove_rating_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="producer",
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
