# Generated by Django 5.2 on 2025-04-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_remove_movie_producer_movie_director"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="description",
        ),
    ]
