# Generated by Django 5.2 on 2025-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="movies/default_movie.jpg", upload_to="movies"
            ),
        ),
    ]
