# Generated by Django 5.2 on 2025-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=100),
        ),
    ]
